apiVersion: 1

datasources:
  - name: JobStore
    type: postgres
    uid: jobstore
    access: proxy
    url: jobmarket-postgres:5432
    database: jobdb
    user: jobuser
    secureJsonData:
      password: ${GF_DATASOURCE_POSTGRES_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
