apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://jobmarket-prometheus:9090
    isDefault: false
    jsonData:
      timeInterval: 15s
